"""Ajout nom/Prenom

Revision ID: bb68a8a2bb79
Revises: 14165c2d5561
Create Date: 2025-01-14 14:51:16.192515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb68a8a2bb79'
down_revision = '14165c2d5561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prenom', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nom', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('nom')
        batch_op.drop_column('prenom')

    # ### end Alembic commands ###
